200.install=安装部署
400.configuration-management=配置参数
500.connection-management=连接管理
600.data-routing=数据路由
700.high-availability=高可用机制
900.o-m-guide=运维
  100.troubleshooting=问题排查
  400.routing-diagnosis=路由诊断
    300.diagnosis-point-troubleshooting=诊断点排查
1000.release-notes=版本发布记录
  110.enterprise-edition-history-release=企业版
    1000.V4.2-ee=V4.2
    1010.V4.1-ee=V4.1
    1020.V4.0-ee=V4.0
    2200.V3.2-ee=V3.2
  120.community-edition-history-release=社区版
    1000.V4.2-ce=V4.2
    1010.V4.1-ce=V4.1
    1020.V4.0-ce=V4.0
