200.install=Installation and deployment
400.configuration-management=Configuration parameter
  200.dynamically-effective=Parameters that take effect dynamically
  300.restart-takes-effect=Parameters that take effect after a restart
500.connection-management=Connection management
600.data-routing=Data routing
  400.intra-tenant-routing=Intra-tenant routing
700.high-availability=High availability mechanism
900.o-m-guide=Operation and maintenance
  100.troubleshooting=Troubleshooting
  400.routing-diagnosis=Routing diagnostics
    300.diagnosis-point-troubleshooting=Diagnostic point troubleshooting
1000.release-notes=Release Notes
  110.enterprise-edition-history-release=Enterprise Edition
    1000.V4.2-ee=V4.2
    1010.V4.1-ee=V4.1
    1020.V4.0-ee=V4.0
    2200.V3.2-ee=V3.2
  120.community-edition-history-release=Community Edition
    1000.V4.2-ce=V4.2
    1010.V4.1-ce=V4.1
    1020.V4.0-ce=V4.0
