2.install=Installation and deployment
4.configuration-management=Configuration parameter
6.data-routing=Data routing
7.high-availability=High availability mechanism
9.o-m-guide=Operation and maintenance
1.troubleshooting=Troubleshooting